import type { TripItinerary } from '../../../types/itinerary'

export const mockTokyoTrip: TripItinerary = {
  id: 'trip-001',
  userId: 'user-001',
  title: 'Tokyo & Kyoto Adventure',
  startDate: '2026-04-10T00:00:00Z',
  endDate: '2026-04-14T00:00:00Z',
  destinations: ['Tokyo', 'Kyoto'],
  items: [
    {
      id: 'item-001',
      dayIndex: 0,
      startTime: '2026-04-10T10:30:00Z',
      endTime: '2026-04-10T14:00:00Z',
      category: 'transit',
      title: 'Flight NRT Arrival',
      description: 'Arrive at Narita International Airport',
      transitMode: 'flight',
      fromLocation: 'San Francisco (SFO)',
      toLocation: 'Tokyo Narita (NRT)',
      vendor: 'Japan Airlines',
      confirmationNumber: 'JL005-XYZW',
      status: 'confirmed',
    },
    {
      id: 'item-002',
      dayIndex: 0,
      startTime: '2026-04-10T15:00:00Z',
      category: 'lodging',
      title: 'Hotel Cerulean Tower',
      description: 'Check in to hotel in Shibuya',
      location: 'Shibuya, Tokyo',
      address: '26-1 Sakuragaokacho, Shibuya City, Tokyo 150-8512',
      checkIn: '2026-04-10T15:00:00Z',
      checkOut: '2026-04-12T11:00:00Z',
      confirmationNumber: 'CT-2026-4412',
      status: 'confirmed',
      cost: 560,
      currency: '$',
    },
    {
      id: 'item-003',
      dayIndex: 0,
      startTime: '2026-04-10T19:00:00Z',
      category: 'meal',
      title: 'Gonpachi Nishiazabu',
      description: 'Dinner at the restaurant that inspired Kill Bill',
      location: 'Nishiazabu, Tokyo',
      mealType: 'dinner',
      cuisine: 'Japanese',
      status: 'confirmed',
      confirmationNumber: 'GP-9981',
    },
    {
      id: 'item-004',
      dayIndex: 1,
      startTime: '2026-04-11T08:00:00Z',
      category: 'meal',
      title: 'Tsukiji Outer Market',
      description: 'Morning sushi breakfast at the market',
      location: 'Tsukiji, Tokyo',
      mealType: 'breakfast',
      cuisine: 'Sushi',
    },
    {
      id: 'item-005',
      dayIndex: 1,
      startTime: '2026-04-11T10:00:00Z',
      endTime: '2026-04-11T12:00:00Z',
      category: 'reservation',
      title: 'TeamLab Borderless',
      description: 'Digital art museum experience',
      location: 'Azabudai Hills, Tokyo',
      vendor: 'TeamLab',
      confirmationNumber: 'TL-20260411-002',
      status: 'confirmed',
      cost: 38,
      currency: '$',
    },
    {
      id: 'item-006',
      dayIndex: 1,
      startTime: '2026-04-11T13:00:00Z',
      category: 'meal',
      title: 'Ichiran Ramen Shibuya',
      description: 'Solo booth ramen experience',
      location: 'Shibuya, Tokyo',
      mealType: 'lunch',
      cuisine: 'Ramen',
    },
    {
      id: 'item-007',
      dayIndex: 2,
      startTime: '2026-04-12T07:30:00Z',
      category: 'transit',
      title: 'Shinkansen to Kyoto',
      description: 'Bullet train Tokyo Station to Kyoto Station',
      transitMode: 'train',
      fromLocation: 'Tokyo Station',
      toLocation: 'Kyoto Station',
      vendor: 'JR Central',
      confirmationNumber: 'NOZOMI-224',
      status: 'confirmed',
    },
    {
      id: 'item-008',
      dayIndex: 2,
      startTime: '2026-04-12T14:00:00Z',
      category: 'reservation',
      title: 'Fushimi Inari Shrine Tour',
      description: 'Guided tour of the thousand torii gates',
      location: 'Fushimi-ku, Kyoto',
      vendor: 'Kyoto Tours Co.',
      status: 'pending',
      cost: 45,
      currency: '$',
    },
    {
      id: 'item-009',
      dayIndex: 3,
      startTime: '2026-04-13T09:00:00Z',
      category: 'activity',
      title: 'Arashiyama Bamboo Grove',
      description: 'Walk through the iconic bamboo forest',
      location: 'Arashiyama, Kyoto',
    },
    {
      id: 'item-010',
      dayIndex: 4,
      startTime: '2026-04-14T11:00:00Z',
      category: 'transit',
      title: 'Return Flight',
      description: 'Fly back from Kansai International Airport',
      transitMode: 'flight',
      fromLocation: 'Osaka Kansai (KIX)',
      toLocation: 'San Francisco (SFO)',
      vendor: 'ANA',
      confirmationNumber: 'NH107-ABCD',
      status: 'confirmed',
    },
  ],
  createdAt: '2026-03-15T12:00:00Z',
  updatedAt: '2026-03-18T09:30:00Z',
}
